// <auto-generated />
namespace CLINICAMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CM1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CM1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805211529300_CM1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
